name: polymer_ui_elements
version: 0.0.13
authors: 
- Erik Grimes <erik.grimes@gmail.com>
- Günter Zöchbauer <guenter@gzoechbauer.com>
description: >
  A Dart port of polymer-ui-elements 
  (https://github.com/Polymer/polymer-ui-elements).
homepage: https://github.com/ErikGrimes/polymer_ui_elements
documentation: http://erikgrimes.github.io/polymer_elements/docs/index.html
environment:
  sdk: '>=0.8.10 <0.8.11'
dependencies:
  polymer: any
  polymer_elements: any
dev_dependencies:
  unittest: any

