name: polymer_ui_elements
version: 0.0.9
authors: 
- Erik Grimes <erik.grimes@gmail.com>
- Günter Zöchbauer <guenter@gzoechbauer.com>
description: A Dart port of polymer-ui-elements (https://github.com/Polymer/polymer-ui-elements).
homepage: https://github.com/ErikGrimes/polymer_ui_elements
environment:
  sdk: '>=0.8.9 <0.8.11'
dependencies:
  polymer: any
dev_dependencies:
  unittest: any
transformers:
- polymer:
    entry_points: 
    - example/polymer_ui_arrow_demo.html
    - example/polymer_ui_icon_button.html
    - example/ui_arrow_example.html
      
