name: polymer_ui_elements
version: 0.1.3
authors:
- Erik Grimes <erik.grimes@gmail.com>
- Günter Zöchbauer <guenter@gzoechbauer.com>
description: >
  A Dart port of polymer-ui-elements
  (https://github.com/Polymer/polymer-ui-elements).
homepage: https://github.com/ErikGrimes/polymer_ui_elements
documentation: http://erikgrimes.github.io/polymer_elements/docs/index.html
environment:
  sdk: ">=1.0.0 <2.0.0"
dependencies:
  polymer: ">=0.10.0-pre.5 <=1.0.0"

dependency_overrides:
  polymer_elements:
    git: https://github.com/ErikGrimes/polymer_elements
dev_dependencies:
  unittest:  ">=0.10.1+1 <1.0.0"
transformers:
- polymer:
    entry_points:
